### PR TITLE
B-Tagged Changes and Category selections 

### PR DESCRIPTION
**Pull request by SangMLee**
B-Jets now only run though the jets that pass jets selection. 
VBF and GGF categories must now have atlas one Jet that has pT greater than 40GeV 
HSubmit.py now reorganizes the output depending on what the user wants
Rochester correction files are now included within the GitHub itself.

### CODE REVIEW

**Comment by jshlee** [comment]
remove the rc data

**Comment by SangMLee** [comment]
I removed the rc data

**Comment by jshlee** [comment]
there are conflicts
do 

git pull origin cat80x

**Comment by jshlee** [comment]
guess this can be closed?

**Comment by SangMLee** [comment]
Yep. 
Doing it the other was was way faster.

**Pull request closed without merging**
